#!/usr/bin/python3
"""
 __        __   _       ____               _____           _
 \ \      / /__| |__   |  _ \  _____   __ |_   _|__   ___ | |___
  \ \ /\ / / _ \ '_ \  | | | |/ _ \ \ / /   | |/ _ \ / _ \| / __|
   \ V  V /  __/ |_) | | |_| |  __/\ V /    | | (_) | (_) | \__ \\
    \_/\_/ \___|_.__/  |____/ \___| \_/     |_|\___/ \___/|_|___/

  Power by: PHILIPPE ASSIS
  Oficial repository: https://github.com/PhilippeAssis/webdevtools
  Version: 1.0

 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
 $$                                                              $$
 $$ LICENSE                                                      $$
 $$                                                              $$
 $$ Copyright 2015 PHILIPPE ASSIS                                $$
 $$ Licensed under the Apache License,                           $$
 $$ Version 2.0 (the “License”);                                 $$
 $$ you may not use this file except in compliance with the      $$
 $$ License. You may obtain a copy of the License at             $$
 $$ http://www.apache.org/licenses/LICENSE-2.0                   $$
 $$                                                              $$
 $$ Unless required by applicable law or agreed to in writing,   $$
 $$ software distributed under the License is distributed on an  $$
 $$ “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, $$
 $$ either express or implied. See the License for the specific  $$
 $$ language governing permissions and limitations under the     $$
 $$ License.                                                     $$
 $$                                                              $$
 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
"""
import os, random, tools



print("All auterações made Web Dev Tools alert will be maintained even if the program is uninstalled. They should be modified manually.")

if tools.query('Are you sure you want to uninstall the Web Dev Tools?',default="no") is True:
    os.system("sudo rm /usr/local/bin/devhost")
    os.system("sudo rm /usr/local/bin/devsite")
    print('WDT: Unfortunately Web Dev Tools has been successfully uninstalled... Goodbye :(')
else:
    tanks = random.choice(['I like it here.','I believe that we will be great friends.','We will be happy together.'])
    print('Thank you for not remove me ... %s' % tanks)