#!/usr/bin/python3
"""
 __        __   _       ____               _____           _
 \ \      / /__| |__   |  _ \  _____   __ |_   _|__   ___ | |___
  \ \ /\ / / _ \ '_ \  | | | |/ _ \ \ / /   | |/ _ \ / _ \| / __|
   \ V  V /  __/ |_) | | |_| |  __/\ V /    | | (_) | (_) | \__ \\
    \_/\_/ \___|_.__/  |____/ \___| \_/     |_|\___/ \___/|_|___/

  Power by: PHILIPPE ASSIS
  Oficial repository: https://github.com/PhilippeAssis/webdevtools
  Version: 1.0

 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
 $$                                                              $$
 $$ LICENSE                                                      $$
 $$                                                              $$
 $$ Copyright 2015 PHILIPPE ASSIS                                $$
 $$ Licensed under the Apache License,                           $$
 $$ Version 2.0 (the “License”);                                 $$
 $$ you may not use this file except in compliance with the      $$
 $$ License. You may obtain a copy of the License at             $$
 $$ http://www.apache.org/licenses/LICENSE-2.0                   $$
 $$                                                              $$
 $$ Unless required by applicable law or agreed to in writing,   $$
 $$ software distributed under the License is distributed on an  $$
 $$ “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, $$
 $$ either express or implied. See the License for the specific  $$
 $$ language governing permissions and limitations under the     $$
 $$ License.                                                     $$
 $$                                                              $$
 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
"""
import os, shutil
from optparse import OptionParser

from lib.tools import tools
from lib.apache2 import apache2
from lib.hosts import hosts





# Setting parameters
usage = "usage: %prog [action*] url* [path|ip] [ip] [options]"
parser = OptionParser(usage=usage)
parser.add_option("--auto", dest="auto", help="Using default settings if the custom is not declared.", default='1')
parser.add_option("--port", dest="port", help="Port (Default 80)", default='80')
parser.add_option("--path", dest="path", help="To declare te removal, remove the site.py directory completely",
                  default=False, action="store_true")
parser.add_option("--notcreatedir", dest="notcreatedir",
                  help="Does not create directories if the specified path does not exist (Defaul: True)", default=False,
                  action="store_true")
parser.add_option("-i", "--ip", dest="ip",
                  help="IP for which the URL address should be directed to when the host is locally generated (Default 127.0.0.1)",
                  default='127.0.0.1')
parser.add_option("-l", "--local", dest="host",
                  help="By declaring -l, will be created an entry in /etc/hosts to the current site.py", default=False,
                  action="store_true")
parser.add_option("-r", "--remove", dest="remove", help="Remove site.py", default=False, action="store_true")
parser.add_option("-z", "--unzip", dest="unzip", help="Unzip in path", default=None)


(options, args) = parser.parse_args()

# Returning 'help' if no argument is declared
if len(args) == 0:
    os.system("webdev -h")
    exit(0)

# Defining arguments
action = args[0]
name = args[1]

if name is None:
    print(
        "ERROR: the url of the site.py is required. Use '-s www.example.com' to declare the url or '-h' for more details.")
    exit(0)

if len(args) > 2:
    if action == 'site':
        path = args[2]
        if len(args) > 3:
            ip = args[3]
        else:
            ip = options.ip
    elif action == 'host':
        ip = args[2]
else:
    path = None
    ip = options.ip

# Action of command 'site'
if action == 'site':
    if options.remove is False and path is None and options.auto is '1':
        print("As the directory path is not specified, '/var/www/'" + name + " is created")
        path = '/var/www/' + name
    elif options.remove is True and path is None:
        # Finding path in the conf apache
        path = tools.locateLine("/etc/apache2/sites-available/%s.conf" % name, 'DocumentRoot')

        if path is not None:
            for ch in ['DocumentRoot', ' ', '\'', '\n']:
                path = path.replace(ch, '')
        else:
            print('Path not found, action aborted.\n')
            exit(0)

    # Instantiating classes
    apache = apache2(name, path)
    host = hosts(name, ip)


    # Evaluating build directory or removal
    if os.path.exists(path) is False and options.remove is False:
        if options.notcreatedir is False:
            os.makedirs(path)
        else:
            print('The directory path does not exist. Action aborted.\n')
            exit(0)
    elif os.path.exists(path) is True and options.remove is True and options.path is True:
        if tools.query('Are you sure you want to remove It directory and all its contents?', 'no') is True:
            shutil.rmtree(path)
            print('Directory %s removed.\n' % path)
        else:
            print('Directory %s not removed.\n' % path)


    if options.unzip is not None and options.remove is False:
        print('Unpacking files...\n')
        os.system('sudo unzip %s -d %s' % (options.unzip,path))

    # Adding, updating or removing the conf apache and the host, if necessary
    if options.remove:
        apache.remove()
        host.remove()
    else:
        apache.created(options.port)
        if options.host is True:
            host.created()


# Action of command 'host'
elif action == 'host':
    host = hosts(name, ip)

    if options.remove:
        host.remove()
    else:
        host.created()
